version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: service:rabbitmq
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  rabbitmq:
    image: rabbitmq:latest
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_VHOST=local
    volumes:
      - rabbitmq-data:/data
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward RabbitMQ locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  rabbitmq-data:
